OPENAI_API_TYPE: 'openai' #'azure'  OR 'openai'
# for 'openai'
OPENAI_KEY: 'sk-R78zmhkOsabT9GT02c33Ae1e011f454aA613C769A8D6F8A7' # your openai key
# OPENAI_KEY: 'sk-xxx' # my key
OPENAI_API_BASE: 'https://api.dqwang.group/v1'
MODEL_NAME: 'gpt-3.5-turbo'
# for 'azure'
AZURE_MODEL: 'XXXXX' # your deploment_model_name 
AZURE_API_BASE: https://xxxxxxxx.openai.azure.com/ # your deployment endpoint
AZURE_API_KEY: 'xxxxxx' # your deployment key
AZURE_API_VERSION: '2023-03-15-preview'